[package]
name = "webb-proposals"
version = "0.3.8"
edition = "2021"
description = "Webb Protocol Proposals Specification & Implementation (part of webb-rs SDK)"
categories = ["encoding", "no-std"]
keywords = ["webb", "proposals", "protocol", "blockchain"]
readme = "../README.md"
repository = "https://github.com/webb-tools/webb-rs"
license = "Apache-2.0"

[dependencies]
scale-codec = { package = 'parity-scale-codec', version = '3.0.0', default-features = false, optional = true }
scale-info = { version = "2.1.1", default-features = false, optional = true }
num-traits = { version = "0.2.8", default-features = false }
typed-builder = { version = "0.10.0", default-features = false, optional = true }
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
cosmwasm-std = "1.0.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
hex-literal = "0.3"
hex = "0.4.3"

[features]
default = ["std", "evm", "substrate", "scale", "cosmwasm"]
std = ["scale-codec/std", "scale-info/std", "num-traits/std"]
scale = ["scale-codec", "scale-info/derive"]
evm = []
substrate = ["scale-codec", "typed-builder"]
cosmwasm = []